network.host: 0.0.0.0
# this might have some security issues: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#modules-scripting
script.engine.groovy.inline.aggs: on
