version: '2'
services:

  # Web UI
  bpo-web-ui:
    build:
      context: .
      dockerfile: Dockerfile.bpo-web-ui
    ports:
      - "80:5000"
    volumes:
      - .:/code/bpo-web-ui
    depends_on:
      - elasticsearch

  # Elasticsearch - as a db/cache and a search engine
  elasticsearch:
    image: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  # Service listening to fedmsg and updating Elasticsearch
  bpo-updater-fedmsg:
    build:
      context: .
      dockerfile: Dockerfile.bpo-updater-fedmsg
    volumes:
      - .:/code/bpo-updater-fedmsg
      - ./config/dev/fedmsg.d:/etc/fedmsg.d
    depends_on:
      - elasticsearch

  # Service that creates data mappings in Elasticsearch and dies. Poor service!
  bpo-updater-mappings:
    build:
      context: .
      dockerfile: Dockerfile.bpo-updater-mappings
    volumes:
      - .:/code/bpo-updater-mappings
    depends_on:
      - elasticsearch

  #====================================================================#
  # Following are supportive services for development, not used in production#
  #====================================================================#

  # Creates testing data in elasticsearch
  bpo-updater-testing-data:
    build:
      context: .
      dockerfile: Dockerfile.bpo-updater-testing-data
    volumes:
      - .:/code/bpo-updater-testing-data
    depends_on:
      - elasticsearch

  # Custom instance of fedmsg to be accessible by other containers
  fedmsg-relay:
    build:
      context: .
      dockerfile: Dockerfile.fedmsg-relay
    volumes:
      - .:/code/fedmsg-relay
      - ./config/dev/fedmsg.d:/etc/fedmsg.d

  # Emits testing fedmsg messages mainly to test the fedmsg updater
  fedmsg-emitter:
    build:
      context: .
      dockerfile: Dockerfile.fedmsg-emitter
    depends_on:
      - fedmsg-relay
    volumes:
      - .:/code/fedmsg-emitter
      - ./config/dev/fedmsg.d:/etc/fedmsg.d
